kind: pipeline
type: docker
name: build

trigger:
  event:
  - push
  - custom
  - pull_request
  - rollback

steps:
- name: uncrustify
  image: gcc
  commands:
  - apt-get update
  - apt-get install -y cmake
  - ./uncrustify.sh
  - git diff --exit-code

- name: build
  image: gcc
  commands:
  - apt-get update
  - apt-get install -y libfdisk-dev
  - make

- name: build with address and leak
  image: gcc
  commands:
  - apt-get update
  - apt-get install -y libfdisk-dev
  - CFLAGS="-fsanitize=address -fsanitize=leak -g" LDFLAGS="-fsanitize=address -fsanitize=leak" make
